openapi: 3.0.3
info:
  title: National Insurance Test Support
  version: "1.0"
servers:
- url: https://test-api.service.hmrc.gov.uk
paths:
  /national-insurance-test-support/sa/{utr}/annual-summary/{taxYear}:
    post:
      summary: Create National Insurance summary test data
      description: Lets you create National Insurance contributions test data
      operationId: createNationalInsuranceSummaryTestData
      parameters:
      - name: utr
        in: path
        description: The 10 digit self-assessment UTR for the individual.
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: "2234567890"
      - name: taxYear
        in: path
        description: The tax year for the National Insurance contribution being created.
        required: true
        style: simple
        explode: false
        schema:
          pattern: "^[0-9]{4}-[0-9]{2}$"
          type: string
          example: 2016-17
      - name: Accept
        in: header
        description: "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)\
          \ of the API to be used."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/vnd.hmrc.1.0+json
      - name: Content-Type
        in: header
        description: "Specifies the format of the request body, which must be JSON."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          enum:
          - application/json
      - name: Authorization
        in: header
        description: "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints)."
        required: true
        style: simple
        explode: false
        schema:
          type: string
          example: Bearer 59fc92c1cdf0b8ef1f138a702effdbd2
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                scenario:
                  type: object
                  description: The scenario to create test data for National Insurance
                  oneOf:
                  - title: firstScenario
                    type: string
                    description: Standard happy path test scenario (default)
                    enum:
                    - HAPPY_PATH_1
                  - title: secondScenario
                    type: string
                    description: Happy path test scenario with different values
                    enum:
                    - HAPPY_PATH_2
              description: Create National Insurance summary test data request
            examples:
              happy-path-1:
                $ref: '#/components/examples/requestHappyPath1'
              happy-path-2:
                $ref: '#/components/examples/requestHappyPath2'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                required:
                - class1
                - class2
                - maxNICsReached
                type: object
                properties:
                  class1:
                    title: class1
                    required:
                    - totalNICableEarnings
                    type: object
                    properties:
                      totalNICableEarnings:
                        type: number
                        description: Total Class 1 earnings subject to National Insurance
                          contributions between the Primary Threshold and the Upper
                          Earnings Limit
                        example: 10
                  class2:
                    title: class2
                    required:
                    - totalDue
                    type: object
                    properties:
                      totalDue:
                        type: number
                        description: Total Class 2 National Insurance contributions
                          due
                        example: 10
                  maxNICsReached:
                    type: boolean
                    description: A flag indicating whether the maximum National Insurance
                      contributions has been reached
                    example: false
                description: Create National Insurance summary test data response
              examples:
                happy-path-1:
                  description: Response for scenario HAPPY_PATH_1
                  value:
                    class1:
                      totalNICableEarnings: 10
                    class2:
                      totalDue: 20
                    maxNICsReached: false
                happy-path-2:
                  description: Response for scenario HAPPY_PATH_2
                  value:
                    class1:
                      totalNICableEarnings: 17
                    class2:
                      totalDue: 319.57
                    maxNICsReached: true
      deprecated: false
      security:
      - application-restricted: []
components:
  schemas:
    class1:
      title: class1
      required:
      - totalNICableEarnings
      type: object
      properties:
        totalNICableEarnings:
          type: number
          description: Total Class 1 earnings subject to National Insurance contributions
            between the Primary Threshold and the Upper Earnings Limit
          example: 10
    class2:
      title: class2
      required:
      - totalDue
      type: object
      properties:
        totalDue:
          type: number
          description: Total Class 2 National Insurance contributions due
          example: 10
    nationalInsuranceTestSupportSaAnnualSummaryRequest:
      title: nationalInsuranceTestSupportSaAnnualSummaryRequest
      type: object
      properties:
        scenario:
          type: object
          description: The scenario to create test data for National Insurance
          oneOf:
          - title: firstScenario
            type: string
            description: Standard happy path test scenario (default)
            enum:
            - HAPPY_PATH_1
          - title: secondScenario
            type: string
            description: Happy path test scenario with different values
            enum:
            - HAPPY_PATH_2
      description: Create National Insurance summary test data request
    nationalInsuranceTestSupportSaAnnualSummaryResponse:
      title: nationalInsuranceTestSupportSaAnnualSummaryResponse
      required:
      - class1
      - class2
      - maxNICsReached
      type: object
      properties:
        class1:
          title: class1
          required:
          - totalNICableEarnings
          type: object
          properties:
            totalNICableEarnings:
              type: number
              description: Total Class 1 earnings subject to National Insurance contributions
                between the Primary Threshold and the Upper Earnings Limit
              example: 10
        class2:
          title: class2
          required:
          - totalDue
          type: object
          properties:
            totalDue:
              type: number
              description: Total Class 2 National Insurance contributions due
              example: 10
        maxNICsReached:
          type: boolean
          description: A flag indicating whether the maximum National Insurance contributions
            has been reached
          example: false
      description: Create National Insurance summary test data response
    firstScenario:
      title: firstScenario
      type: string
      description: Standard happy path test scenario (default)
      enum:
      - HAPPY_PATH_1
    secondScenario:
      title: secondScenario
      type: string
      description: Happy path test scenario with different values
      enum:
      - HAPPY_PATH_2
  parameters:
    utr:
      name: utr
      in: path
      description: The 10 digit self-assessment UTR for the individual.
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: "2234567890"
    taxYear:
      name: taxYear
      in: path
      description: The tax year for the National Insurance contribution being created.
      required: true
      style: simple
      explode: false
      schema:
        pattern: "^[0-9]{4}-[0-9]{2}$"
        type: string
        example: 2016-17
    acceptHeader:
      name: Accept
      in: header
      description: "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning)\
        \ of the API to be used."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/vnd.hmrc.1.0+json
    contentTypeHeader:
      name: Content-Type
      in: header
      description: "Specifies the format of the request body, which must be JSON."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        enum:
        - application/json
    authorizationHeader:
      name: Authorization
      in: header
      description: "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/application-restricted-endpoints)."
      required: true
      style: simple
      explode: false
      schema:
        type: string
        example: Bearer 59fc92c1cdf0b8ef1f138a702effdbd2
  examples:
    requestHappyPath1:
      description: Payload for scenario HAPPY_PATH_1
      value:
        scenario: HAPPY_PATH_1
    requestHappyPath2:
      description: Payload for scenario HAPPY_PATH_2
      value:
        scenario: HAPPY_PATH_2
    responseHappyPath1:
      description: Response for scenario HAPPY_PATH_1
      value:
        class1:
          totalNICableEarnings: 10
        class2:
          totalDue: 20
        maxNICsReached: false
    responseHappyPath2:
      description: Response for scenario HAPPY_PATH_2
      value:
        class1:
          totalNICableEarnings: 17
        class2:
          totalDue: 319.57
        maxNICsReached: true
  securitySchemes:
    application-restricted:
      type: oauth2
      description: "HMRC supports OAuth 2.0 for authenticating [application-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/application-restricted-endpoints)\
        \ API requests using an OAuth 2.0 Bearer Token in the Authorization header."
      flows:
        clientCredentials:
          tokenUrl: https://test-api.service.hmrc.gov.uk/oauth/token
          scopes: {}
